### ISSUE TITLE
Specifications for the ball bearings 

### ISSUE THREAD

**Issue by Shally1986** [DrNebin/RC_Car#1]
Hello , 

I'm interested to build the rc car . Can you provide me the specification of the ball bearings needed 

Thanks 
Kushal

**Comment by DrNebin** [comment]
Hello. Thanks for your question. The bearing is the FR188-Z. An example can be found here: https://bearingsdirect.com/fr188-zz-flanged-miniature-ball-bearing-1-4x1-2x3-16-shielded-rif814zz/

**Comment by Shally1986** [comment]
Thanks for your reply.

Count is 4 ?

Thanks
Kushal Sahota

**Comment by DrNebin** [comment]
Yes. DevinOn Nov 16, 2023, at 7:55 AM, Shally1986 ***@***.***> wrote:﻿
Thanks for your reply.



Count is 4 ?



Thanks

Kushal Sahota
